// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";
import config from "./src/config/env";

interface AppConfig {
  [key: string]: any;
}

const typedConfig = config as AppConfig;

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: typedConfig.DATABASE_URL,
  },
});
